--- 
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: run apt-get update and install python3
      raw: "{{ item }}"
      loop:
        - apt-get update
        - apt-get -y install python3
      #become: true